# Generated by Django 5.2.6 on 2026-07-08 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], db_index=True, default='queued', max_length=16)),
                ('stage', models.CharField(blank=True, choices=[('ingest', 'ingest'), ('scenes', 'scenes'), ('features', 'features'), ('scoring', 'scoring'), ('narrative', 'narrative'), ('render', 'render')], max_length=16, null=True)),
                ('progress', models.SmallIntegerField(default=0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('precision_at_5', models.FloatField()),
                ('auprc', models.FloatField()),
                ('ci_low', models.FloatField()),
                ('ci_high', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_runs', to='promoapp.promojob')),
            ],
        ),
        migrations.CreateModel(
            name='PromoOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='output/')),
                ('aspect', models.CharField(choices=[('16:9', '16:9'), ('9:16', '9:16'), ('1:1', '1:1')], default='16:9', max_length=8)),
                ('duration_s', models.FloatField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='promoapp.promojob')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField()),
                ('start_s', models.FloatField()),
                ('end_s', models.FloatField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='promoapp.promojob')),
            ],
            options={
                'unique_together': {('job', 'index')},
            },
        ),
        migrations.CreateModel(
            name='SegmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.FloatField(blank=True, null=True)),
                ('audio', models.FloatField(blank=True, null=True)),
                ('motion', models.FloatField(blank=True, null=True)),
                ('quality', models.FloatField(blank=True, null=True)),
                ('transcript', models.FloatField(blank=True, null=True)),
                ('fused', models.FloatField(db_index=True)),
                ('selected', models.BooleanField(default=False)),
                ('narrative_role', models.CharField(blank=True, choices=[('hook', 'hook'), ('build', 'build'), ('climax', 'climax'), ('outro', 'outro')], max_length=8, null=True)),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='promoapp.scene')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='input/')),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_s', models.FloatField(default=0)),
                ('fps', models.FloatField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('has_audio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='promojob',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='promoapp.videoupload'),
        ),
        migrations.AddIndex(
            model_name='promojob',
            index=models.Index(fields=['status', 'created_at'], name='promoapp_pr_status_9542b1_idx'),
        ),
    ]
